### ISSUE TITLE
SCPI/JD documentation?

### ISSUE THREAD

**Issue by 9600** [tomahawk28/cell#7]
We've been trying to use this with a Gencomm GC747A and having limited success, but also wondered if you could point us in the direction of documentation for the "JD" and SCPI commands supported by these instruments?

**Comment by tomahawk28** [comment]
Hi, 
I'm no longer working in JDSU, So I can't give you any help with that. 
If you contact Viavi solutions (they changed the name of the company) with your model number, they might give you SCPI commands.
Sorry that I can't help you with that.

**Comment by 9600** [comment]
Thanks for getting back to me, will get in touch with Viavi.
